Repository helpwave/web, pull requests merged in 2022-10, with the labels that each got.

#14 Add `useLanguage` hook and `withTranslation` hoc
  .gitignore
  app/.eslintrc.js
  app/components/LanguageSwitcher.tsx
  app/components/examples/Title.tsx
  app/hocs/withTranslation.tsx
  app/hooks/useLanguage.tsx
  app/pages/examples/intl.tsx
Labels: enhancement, hacktoberfest-accepted

#13 `useAuth` hook
  app/hooks/useAuth.ts
  app/package.json
  app/pages/index.tsx
  app/utils/api.ts
  app/utils/config.ts
  app/utils/login.ts
  pnpm-lock.yaml
Labels: enhancement

#17 feat: proper env config loading (#12)
  README.md
  app/.env
  app/README.md
  app/hooks/useAuth.ts
  app/utils/api.ts
  app/utils/config.ts
Labels: hacktoberfest-accepted

#19 editorconfig
  .editorconfig
Labels: documentation, enhancement
