Repository helpwave/web, pull requests merged in 2023-04, with the labels that each got.

#180 Issue/135 select component
  lib/icons/ChevronDown.tsx
  lib/icons/ChevronUp.tsx
  pnpm-lock.yaml
  tasks/components/user_input/Select.tsx
  tasks/package.json
Labels: priority:low, tasks

#204 fix: use consistent title
  tasks/pages/_app.tsx
  tasks/pages/_document.tsx
  tasks/pages/index.tsx
  tasks/pages/login.tsx
  tasks/pages/organizations.tsx
  tasks/pages/organizations/[uuid].tsx
  tasks/pages/profile.tsx
  tasks/pages/settings.tsx
  tasks/pages/ward/[uuid].tsx
  tasks/utils/titleWrapper.ts
Labels: enhancement

#243 Apply Confirm Dialog
  tasks/components/RoomList.tsx
  tasks/components/layout/OrganizationDetails.tsx
  tasks/components/layout/PatientDetails.tsx
  tasks/components/layout/WardDetails.tsx
  tasks/pages/organizations/[uuid].tsx
Labels: tasks

#251 fix: set correct oauth defaults
  tasks/.env
  tasks/utils/config.ts
  tasks/utils/oauth.ts
Labels: bug, tasks

#265 LanguageModal
  lib/components/modals/LanguageModal.tsx
Labels: enhancement, tasks, proffi-proofed

#262 add two column closable sidebar
  lib/components/modals/Modal.tsx
  tasks/components/layout/TwoColumn.tsx
  tasks/pages/_app.tsx
  tasks/pages/organizations.tsx
  tasks/pages/organizations/[uuid].tsx
  tasks/pages/ward/[uuid].tsx
Labels: proffi-proofed, #fixitfelix

#263 add dashboard
  lib/components/TimeDisplay.tsx
  tasks/components/FeatureDisplay.tsx
  tasks/components/cards/OrganizationCard.tsx
  tasks/components/cards/WardCard.tsx
  tasks/components/layout/DashboardDisplay.tsx
  tasks/components/layout/FeatureDetails.tsx
  tasks/mutations/organization_mutations.ts
  tasks/mutations/ward_mutations.tsx
  tasks/pages/index.tsx
Labels: tasks, #fixitfelix

#274 fix: re-implement useAuth to be used with OAuth
  lib/hooks/useLanguage.tsx
  pnpm-lock.yaml
  tasks/components/FeatureDisplay.tsx
  tasks/components/UserMenu.tsx
  tasks/components/cards/UserCard.tsx
  tasks/components/layout/PageWithHeader.tsx
  tasks/hooks/useAuth.ts
  tasks/package.json
  tasks/pages/auth/callback.tsx
  tasks/pages/auth/index.tsx
  tasks/pages/examples/test.tsx
  tasks/pages/index.tsx
  tasks/pages/ward/[uuid].tsx
  tasks/utils/config.ts
  tasks/utils/login.ts
  tasks/utils/oauth.ts
Labels: enhancement

#278 make no subtasks be shown as full progress
  tasks/components/cards/TaskCard.tsx
Labels: proffi-proofed

#300 fix(web): Add a visual limits to the room name
  tasks/components/RoomList.tsx
  tasks/components/cards/WardCard.tsx
Labels: bug, tasks

#310 chore: optimize renovate settings
  renovate.json
Labels: deps, devops
