Repository helpwave/web, pull requests merged in 2023-03, with the labels that each got.

#85 chore(app): add gRPC-web example
  app/README.md
  app/generated/Ward-svcServiceClientPb.ts
  app/generated/ward-svc_pb.d.ts
  app/generated/ward-svc_pb.js
  app/package.json
  app/pages/index.tsx
  pnpm-lock.yaml
Labels: dashboard

#86 Radical Landing-Page Reduction
  .husky/pre-commit
  landing-page/components/Header.tsx
  landing-page/components/sections/StartSection.tsx
  landing-page/pages/index.tsx
  lib/hooks/useLanguage.tsx
Labels: landing-page, priority:high

#87 add PillLabels
  app/components/PillLabel.tsx
  app/components/PillLabelsColumn.tsx
  lib/twind/config.ts
Labels: enhancement

#129 chore(deps): add Dependabot
  .github/dependabot.yaml
Labels: deps
