Repository helpwave/web, pull requests merged in 2024-04, with the labels that each got.

#978 chore: translate story and tasks page
  landing-page/components/sections/story/StartSection.tsx
  landing-page/components/sections/tasks/FeatureSection.tsx
  landing-page/components/sections/tasks/ReachoutSection.tsx
  landing-page/components/sections/tasks/StartSection.tsx
Labels: landing-page

#988 Update acqusition texts
  landing-page/components/sections/mediQuu/BrandInformationSection.tsx
  landing-page/components/sections/mediQuu/Header.tsx
  landing-page/components/sections/mediQuu/InformationSection.tsx
  landing-page/components/sections/mediQuu/MediQuuFAQ.tsx
  landing-page/components/sections/mediQuu/RoadmapSection.tsx
  landing-page/pages/mediquu/index.tsx
  lib/components/MarkdownInterpreter.tsx
Labels: priority:high

#991 chore: fix wording and typos
  landing-page/components/sections/mediQuu/BrandInformationSection.tsx
  landing-page/components/sections/mediQuu/RoadmapSection.tsx
Labels: chore

#1000 fix newLine in MarkdownInterpreter
  landing-page/components/sections/mediQuu/InformationSection.tsx
  lib/components/MarkdownInterpreter.tsx
  lib/stories/other/MarkdownInterpreter.stories.tsx
Labels: priority:high

#1041 Add partner 'Collective Incubator'
  landing-page/components/sections/landing/Partners.tsx
Labels: landing-page, #fixitfelix
